USE [DWPROD]
GO

/****** Object:  Table [NextGen].[trans_detail]    Script Date: 1/26/2024 12:41:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[F_Transactions](
		Practice_ID CHAR(4) NOT NULL,
		Guarantor_ID UNIQUEIDENTIFIER NOT NULL,
		Enc_ID UNIQUEIDENTIFIER NOT NULL,
		Charge_ID UNIQUEIDENTIFIER NOT NULL,
		Guar_Type CHAR(1) NOT NULL,
		Gross_Charges MONEY NOT NULL,
		COB1_Bal MONEY NOT NULL,
		COB2_Bal MONEY NOT NULL,
		COB3_Bal MONEY NOT NULL,
		Pat_Bal MONEY NOT NULL,
		Tot_Ins_Bal MONEY NOT NULL,
		Ins_Pmt_Amt MONEY NOT NULL,
		Pat_Pmt_Amt MONEY NOT NULL,
		Ins_Adj_Amt MONEY NOT NULL,
		Pat_Adj_Amt MONEY NOT NULL,
		Ins_Ref_Amt MONEY NOT NULL,
		Pat_Ref_Amt MONEY NOT NULL,
		Curr_Enc_Bal MONEY NOT NULL,

 CONSTRAINT [Charge_ID] PRIMARY KEY NONCLUSTERED 
(
	[charge_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]
GO


